# Generated by Django 5.2.4 on 2025-09-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profile_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='https://res.cloudinary.com/ddmslr9na/image/upload/v1234567890/default_profile.jpg', upload_to='profile_images/'),
        ),
    ]
