# Generated by Django 5.2.4 on 2025-10-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_unique_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_moogles_award_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
