# Generated by Django 5.2.4 on 2025-09-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_orderitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='asset_file',
            field=models.FileField(blank=True, null=True, upload_to='order_assets/'),
        ),
    ]
