# Generated by Django 5.2.4 on 2025-10-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_orderitem_asset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='moogles_spent',
            field=models.IntegerField(default=0),
        ),
    ]
