# Generated by Django 5.2.4 on 2025-09-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('emotes', 'Emotes'), ('posters', 'Posters'), ('banners', 'Banners'), ('badges', 'Badges'), ('media_kits', 'Media Kits')], max_length=20),
        ),
    ]
